{% set name = "aff3ct" %}
{% set version = "3.0.2" %}

package:
  name: {{ name }}
  version: {{ version }}


source:
  url: https://github.com/aff3ct/aff3ct.git
  ref: v3.0.2

build:
  number: 0
#  script: echo asd

requirements:
  build:
    - cmake
  run:
    - cmake

test:
  commands:
#    - $PREFIX/bin/aff3ct --version    # [unix]
    - aff3ct --version

about:
  home: https://github.com/aff3ct/aff3ct.git
  license: MIT
  summary: C++ library dedicated to the Forward Error Correction

extra:
  anaconda-services:
    ref: https://anaconda.zendesk.com/agent/tickets/41195
    reason: Northrop Grumman ask
  recipe-maintainers:
    - ianaobi
    - bradley
